
import { PrismaClient } from '@prisma/client'
import { SecurityService } from './security'

const prisma = new PrismaClient()

export class ApprovalService {

  /**
   * Evaluate if an action requires approval based on rules
   */
  static async checkAndCreateRequest(
    userId: string,
    entityType: string, // 'transfer', 'po', 'adjustment'
    entityId: string,
    data: any // { totalAmount: 500000000 }
  ): Promise<boolean> {
    
    // 1. Fetch active rules for this entity type
    const rules = await prisma.approvalRule.findMany({
      where: { entityType, active: true },
      orderBy: { priority: 'asc' }
    })

    for (const rule of rules) {
      const condition = rule.condition as any
      // Simple condition check: field > value
      // Real implementation would use a rule engine
      if (condition.operator === 'gt' && data[condition.field] > condition.value) {
        
        // Create Approval Request
        await prisma.approvalRequest.create({
          data: {
            code: `REQ-${Date.now()}`,
            entityType,
            entityId,
            ruleId: rule.id,
            requesterId: userId,
            status: 'pending',
            note: `Auto-generated by rule: ${rule.name}`
          }
        })
        
        // Block the action
        return true 
      }
    }

    return false // No approval needed
  }

  /**
   * Approve a request
   */
  static async approveRequest(requestId: string, approverId: string, note?: string) {
    const request = await prisma.approvalRequest.findUnique({
      where: { id: requestId },
      include: { rule: true }
    })

    if (!request) throw new Error('Request not found')
    if (request.status !== 'pending') throw new Error('Request is not pending')

    // Check if approver has the role
    const approver = await prisma.user.findUnique({
      where: { id: approverId },
      include: { role: true }
    })

    if (!approver) throw new Error('Approver not found')
    
    // Role check (Simplified)
    // In real app, check if approver.role.name matches request.rule.approverRole
    
    await prisma.approvalRequest.update({
      where: { id: requestId },
      data: {
        status: 'approved',
        approverId,
        approvedAt: new Date(),
        note
      }
    })

    // Execute the blocked action (Callback or State Update)
    // For now, we just log it
    await SecurityService.logAudit(approverId, 'APPROVE', request.entityType, request.entityId, { requestId })
    
    // Here you would trigger the actual business logic (e.g., update Transfer status to 'approved')
    if (request.entityType === 'transfer') {
        await prisma.stockTransfer.update({
            where: { id: request.entityId },
            data: { status: 'approved' }
        })
    }
    
    return true
  }

  static async rejectRequest(requestId: string, approverId: string, note: string) {
    await prisma.approvalRequest.update({
      where: { id: requestId },
      data: {
        status: 'rejected',
        approverId,
        approvedAt: new Date(),
        note
      }
    })
     
    const request = await prisma.approvalRequest.findUnique({ where: { id: requestId }})
    if (request?.entityType === 'transfer') {
        await prisma.stockTransfer.update({
            where: { id: request.entityId },
            data: { status: 'rejected' }
        })
    }
  }
}
